install:
    - appveyor DownloadFile "https://developer.nvidia.com/compute/cuda/8.0/prod/network_installers/cuda_8.0.44_windows_network-exe"
    - cuda_8.0.44_windows_network-exe -s compiler_8.0 cublas_8.0 cublas_dev_8.0 cudart_8.0 curand_8.0 curand_dev_8.0 cusolver_8.0 cusolver_dev_8.0
